/**
 * @generated by scripts/architecture-history.mjs — do not edit.
 *
 * Every recorded measurement of this repo, oldest first. The map's history
 * dropdown reads this; an entry appears only on a day the measurements moved.
 */

export type HistorySnapshot = {
  date: string
  totals: { files: number; loc: number }
  nodes: Record<string, { count: number; loc: number }>
}

export const HISTORY: HistorySnapshot[] = [
  {"date":"2026-08-19","totals":{"files":27,"loc":3982},"nodes":{"api":{"count":1,"loc":157},"serve":{"count":1,"loc":356},"cli":{"count":1,"loc":65},"trace":{"count":1,"loc":208},"ingest":{"count":1,"loc":356},"loaders":{"count":1,"loc":291},"ocr":{"count":1,"loc":111},"health":{"count":1,"loc":101},"fetch":{"count":1,"loc":82},"parsecache":{"count":1,"loc":104},"embedcache":{"count":1,"loc":151},"retrieve":{"count":1,"loc":158},"hybrid":{"count":1,"loc":101},"rerank":{"count":1,"loc":77},"diversify":{"count":1,"loc":95},"parent":{"count":1,"loc":130},"abstain":{"count":1,"loc":95},"generate":{"count":1,"loc":78},"evaluate":{"count":1,"loc":331},"goldenset":{"count":5,"loc":681},"probes":{"count":3,"loc":254}}},
  {"date":"2026-08-20","totals":{"files":27,"loc":4024},"nodes":{"api":{"count":1,"loc":157},"serve":{"count":1,"loc":398},"cli":{"count":1,"loc":65},"trace":{"count":1,"loc":208},"ingest":{"count":1,"loc":356},"loaders":{"count":1,"loc":291},"ocr":{"count":1,"loc":111},"health":{"count":1,"loc":101},"fetch":{"count":1,"loc":82},"parsecache":{"count":1,"loc":104},"embedcache":{"count":1,"loc":151},"retrieve":{"count":1,"loc":158},"hybrid":{"count":1,"loc":101},"rerank":{"count":1,"loc":77},"diversify":{"count":1,"loc":95},"parent":{"count":1,"loc":130},"abstain":{"count":1,"loc":95},"generate":{"count":1,"loc":78},"evaluate":{"count":1,"loc":331},"goldenset":{"count":5,"loc":681},"probes":{"count":3,"loc":254}}},
  {"date":"2026-08-21","totals":{"files":38,"loc":6079},"nodes":{"api":{"count":1,"loc":167},"serve":{"count":1,"loc":591},"cli":{"count":1,"loc":65},"trace":{"count":2,"loc":468},"ingest":{"count":1,"loc":376},"loaders":{"count":1,"loc":305},"ocr":{"count":1,"loc":111},"health":{"count":1,"loc":101},"fetch":{"count":1,"loc":82},"parsecache":{"count":1,"loc":104},"embedcache":{"count":1,"loc":151},"retrieve":{"count":6,"loc":777},"hybrid":{"count":1,"loc":108},"rerank":{"count":1,"loc":77},"diversify":{"count":1,"loc":99},"parent":{"count":1,"loc":130},"abstain":{"count":1,"loc":95},"generate":{"count":1,"loc":158},"evaluate":{"count":6,"loc":1117},"goldenset":{"count":5,"loc":743},"probes":{"count":3,"loc":254}}},
]
