/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'abstain': { count: 1, loc: 95 },
  'api': { count: 1, loc: 157 },
  'cli': { count: 1, loc: 65 },
  'diversify': { count: 1, loc: 95 },
  'embedcache': { count: 1, loc: 151 },
  'evaluate': { count: 1, loc: 331 },
  'fetch': { count: 1, loc: 82 },
  'generate': { count: 1, loc: 78 },
  'goldenset': { count: 5, loc: 681 },
  'health': { count: 1, loc: 101 },
  'hybrid': { count: 1, loc: 101 },
  'ingest': { count: 1, loc: 356 },
  'loaders': { count: 1, loc: 291 },
  'ocr': { count: 1, loc: 111 },
  'parent': { count: 1, loc: 130 },
  'parsecache': { count: 1, loc: 104 },
  'probes': { count: 3, loc: 254 },
  'rerank': { count: 1, loc: 77 },
  'retrieve': { count: 1, loc: 158 },
  'serve': { count: 1, loc: 398 },
  'trace': { count: 1, loc: 208 },
}

export const UNCLAIMED: string[] = []
