/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'abstain': { count: 1, loc: 95 },
  'api': { count: 1, loc: 167 },
  'cli': { count: 1, loc: 65 },
  'diversify': { count: 1, loc: 99 },
  'embedcache': { count: 1, loc: 151 },
  'evaluate': { count: 6, loc: 1117 },
  'fetch': { count: 1, loc: 82 },
  'generate': { count: 1, loc: 158 },
  'goldenset': { count: 5, loc: 743 },
  'health': { count: 1, loc: 101 },
  'hybrid': { count: 1, loc: 108 },
  'ingest': { count: 1, loc: 376 },
  'loaders': { count: 1, loc: 305 },
  'ocr': { count: 1, loc: 111 },
  'parent': { count: 1, loc: 130 },
  'parsecache': { count: 1, loc: 104 },
  'probes': { count: 3, loc: 254 },
  'rerank': { count: 1, loc: 77 },
  'retrieve': { count: 6, loc: 777 },
  'serve': { count: 1, loc: 591 },
  'trace': { count: 2, loc: 468 },
}

export const UNCLAIMED: string[] = [
  'src/fetch_topic.py',
  'src/make_documents.py',
  'src/test_loaders.py',
]
