#!/usr/bin/env node
/**
 * Snapshots the architecture measurements over time, so the map can show how
 * the system grew rather than only how it looks today.
 *
 * Deliberately a separate script from `architecture-sync.mjs`. That file is
 * vendored from the architecture-map skill and should stay byte-identical to
 * upstream so it can be replaced when the skill updates; this is the local
 * addition, and it reuses the exported `measure()` rather than re-implementing
 * the scan. One measurement source, two consumers.
 *
 * A snapshot is written only when the measurements actually differ from the
 * newest one on file. Running this twice on an unchanged tree is a no-op, which
 * is what keeps it safe to run as often as you like -- a history of identical
 * entries would be worse than no history.
 *
 * Snapshots are keyed by date. Re-running on a day that already has one
 * overwrites it, so a day of work leaves one entry rather than thirty.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { measure } from './architecture-sync.mjs'

const ROOT = process.cwd()
const DIR = `${ROOT}/architecture/history`
const OUT = `${ROOT}/architecture/history.generated.ts`

const today = new Date().toISOString().slice(0, 10)

function load() {
  if (!existsSync(DIR)) return []
  return readdirSync(DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(`${DIR}/${f}`, 'utf8')))
}

function totalsOf(nodes) {
  return Object.values(nodes).reduce(
    (acc, m) => ({ files: acc.files + m.count, loc: acc.loc + m.loc }),
    { files: 0, loc: 0 },
  )
}

const result = measure()
const nodes = result.measured
const snapshot = { date: today, totals: totalsOf(nodes), nodes }

const history = load()
const newest = history.filter((h) => h.date !== today).at(-1)
const unchanged = newest && JSON.stringify(newest.nodes) === JSON.stringify(nodes)

if (unchanged) {
  console.log(`architecture history — unchanged since ${newest.date}, nothing written`)
} else {
  mkdirSync(DIR, { recursive: true })
  writeFileSync(`${DIR}/${today}.json`, `${JSON.stringify(snapshot, null, 2)}\n`)
  console.log(`architecture history — recorded ${today}`)
}

// Regenerate the module the bundle imports, from whatever is on disk now.
const all = load()
const body = all
  .map((h) => `  ${JSON.stringify(h)},`)
  .join('\n')

writeFileSync(
  OUT,
  `/**\n * @generated by scripts/architecture-history.mjs — do not edit.\n *\n` +
    ` * Every recorded measurement of this repo, oldest first. The map's history\n` +
    ` * dropdown reads this; an entry appears only on a day the measurements moved.\n */\n\n` +
    `export type HistorySnapshot = {\n` +
    `  date: string\n` +
    `  totals: { files: number; loc: number }\n` +
    `  nodes: Record<string, { count: number; loc: number }>\n` +
    `}\n\n` +
    `export const HISTORY: HistorySnapshot[] = [\n${body}\n]\n`,
)
console.log(`architecture history — ${all.length} snapshot(s) in ${OUT.replace(`${ROOT}/`, '')}`)
