"""Every source document in every corpus, listed — without shipping any of them.

The demo cites its sources by filename: "bird_vocalization.pdf, page 2",
"lora.pdf, page 4". A reader who wants to know *what those files are* has
nowhere to look. The papers themselves are deliberately not in this repository
(see `ATTRIBUTION.md`), and that is the right call, but "not here" and "not
knowable" are different things — a bibliography is metadata, not redistribution,
and it is the difference between a citation and a dead end.

So this writes `docs/corpus-manifest.md` from the built indexes: for each
corpus, every document, its title, the file format, and how many passages it
contributes. Each row is linked to its actual source where the mapping is
knowable rather than guessed — arXiv identifiers for the papers
`src/fetch_corpus.py` names explicitly, and the Wikipedia article for every
ornithology file, since `fetch_topic.slug` is the function that made those
filenames and running it over `fetch_topic.BIRDS` reconstructs the mapping
exactly. The remaining papers came from a topic search, so their title is their
identifier and the title is what is printed.

Generated rather than written, for the reason everything here is generated: a
hand-maintained list of 116 files across three corpora is a list that is wrong
within a month. Run it after re-ingesting anything.

    python src/build_corpus_manifest.py
    python src/build_corpus_manifest.py --check    # exits 1 if it has drifted
"""
import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import corpora                                          # noqa: E402
from fetch_corpus import PAPERS                          # noqa: E402
from fetch_topic import BIRDS, slug                      # noqa: E402

ROOT = Path(__file__).parent.parent
OUT = ROOT / "docs" / "corpus-manifest.md"

# The nineteen papers fetched by identifier. Everything else in the ML and
# finance sets came from a title search, which is why they have no id here --
# arXiv's API returns the paper, and the filename is a slug of its title.
ARXIV_ID = {stem: arxiv_id for arxiv_id, stem in PAPERS}

# The ornithology files are Wikipedia articles rendered into four formats. The
# filename is slug(article title), so running the same function over the same
# list recovers the mapping exactly rather than guessing at it -- and the link
# is what CC BY-SA attribution asks for.
WIKI = {slug(title): title for title in BIRDS}


def documents(cfg: dict) -> list[dict]:
    """One row per source file, from the index rather than from the folder.

    The index is what the system actually searches. A folder can hold a file
    that failed to parse, and listing that would claim a document the retriever
    has never seen.
    """
    store = ROOT / cfg["store"]
    meta_path = store / "metadata.json"
    if not meta_path.exists():
        return []
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    passages = Counter(c["source"] for c in meta)
    titles: dict[str, str] = {}
    for c in meta:
        t = (c.get("title") or "").strip()
        if t and c["source"] not in titles:
            titles[c["source"]] = t

    rows = []
    for name in sorted(passages):
        stem, _, ext = name.rpartition(".")
        rows.append({
            "file": name,
            "title": titles.get(name, ""),
            "format": ext.upper(),
            "passages": passages[name],
            "arxiv": ARXIV_ID.get(stem, ""),
            "wiki": WIKI.get(stem, ""),
        })
    return rows


def render() -> str:
    reg = corpora.registry()
    out = ["# The documents\n\n",
           "Every source file each corpus is built from, with the title "
           "extracted at ingest and\nthe number of passages it contributes. "
           "**The files themselves are not in this\nrepository** — see "
           "[`ATTRIBUTION.md`](../ATTRIBUTION.md) for why, and for how to "
           "rebuild each\nset from its original source.\n\n",
           "Generated by `src/build_corpus_manifest.py` from the built "
           "indexes, so it lists what\nthe retriever can actually see rather "
           "than what happens to be in a folder.\n"]

    for name, cfg in reg.items():
        rows = documents(cfg)
        if not rows:
            continue
        formats = Counter(r["format"] for r in rows)
        total = sum(r["passages"] for r in rows)
        out.append(f"\n## {cfg['label']}\n")
        out.append(f"{len(rows)} documents · {total:,} passages · "
                   + " · ".join(f"{n} {f}" for f, n in formats.most_common())
                   + "\n")
        if any(r["arxiv"] for r in rows):
            out.append(
                "\nWhere an arXiv identifier is given, `src/fetch_corpus.py` "
                "fetched that paper by id.\nThe rest were found by a topic "
                "search (`src/fetch_topic.py`), so the title is the "
                "identifier.\n")
        if any(r["wiki"] for r in rows):
            out.append(
                "\nEach file is one Wikipedia article, rendered into the "
                "format named by its extension —\nthe same article appears as "
                "`.docx` and `.pdf` so that format handling is exercised by "
                "something\nother than PDFs. Published under "
                "[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
                "\n")
        out.append("\n| file | title | passages |\n|---|---|---|\n")
        for r in rows:
            if r["wiki"]:
                # The article title, not the title the extractor found: these
                # files are generated, and what it finds is the filename stem
                # in lower case. The article is the actual source.
                url = "https://en.wikipedia.org/wiki/" + r["wiki"].replace(" ", "_")
                title = f"[{r['wiki']}]({url})"
            else:
                title = r["title"] or "—"
                if r["arxiv"]:
                    title += (f" · [arXiv:{r['arxiv']}]"
                              f"(https://arxiv.org/abs/{r['arxiv']})")
            out.append(f"| `{r['file']}` | {title} | {r['passages']} |\n")

    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the written file is not what this "
                         "would write now")
    args = ap.parse_args()

    body = render()
    if "\n## " not in body:
        print("no built index to read -- run src/ingest.py first")
        return 2

    if args.check:
        if not OUT.exists():
            print(f"{OUT.relative_to(ROOT)} does not exist")
            return 1
        if OUT.read_text(encoding="utf-8") != body:
            print(f"{OUT.relative_to(ROOT)} has drifted from the indexes.\n"
                  f"Run: python src/build_corpus_manifest.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    n = body.count("\n| `")
    print(f"{OUT.relative_to(ROOT)}: {n} documents across "
          f"{body.count(chr(10) + '## ')} corpora")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
