"""Record real traces to JSON, so the demo can be served with no models at all.

The live system needs ~1.5 GB of dependencies and 2 GB of RAM because it holds a
FAISS index, a bi-encoder and a cross-encoder in memory. That rules out every
serverless platform. But a visitor to a *demo* mostly clicks the questions the
front page offers, and those are known in advance -- so their answers can be
computed once, here, on a machine that has the models, and served afterwards by
anything that can return a JSON file.

**What is recorded is not a summary.** Each entry is the exact payload
`/api/chat` returns for that question: every retrieval stage with its ranking
and scores, the fusion arithmetic, what the reranker moved, what the diversity
cap dropped, the verdict and its threshold, and the term attribution. A static
demo built from this shows the same pipeline the live one does, because it is
the same output.

**What it loses**, stated plainly because it is the whole trade: a visitor
cannot ask a question that was not recorded. There is no model to answer one.
A static build should say so rather than presenting a text box that silently
only accepts ten strings.

Generated prose is recorded too when `--generate` is passed, and is labelled in
the payload with the model that wrote it. The interface should attribute it the
same way: "generated by llama3.2" is a materially different claim from an answer
written by a frontier model, and a reader is entitled to know which they are
reading.

    .venv\\Scripts\\python.exe src\\record_static.py --corpus birds
    .venv\\Scripts\\python.exe src\\record_static.py --all --generate
"""
import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import corpora  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent.parent
OUT = ROOT / "static-demo"


def key(question: str) -> str:
    """A stable filename for a question, so the front end can find it.

    A hash rather than a slug: questions contain punctuation, they differ in
    ways a slug flattens ("what is X?" and "what is X" would collide), and the
    front end can compute the same hash from the string it holds.
    """
    return hashlib.sha256(question.strip().lower().encode()).hexdigest()[:16]


def questions_for(cfg: dict, every: bool) -> list[dict]:
    """The questions to record: the offered ones, or the whole golden set."""
    from evaluate import load_cases

    if every:
        answerable, adversarial = load_cases(cfg["golden"])
        return [{"q": c["question"], "id": c["id"],
                 "adversarial": bool(c.get("unanswerable"))}
                for c in answerable + adversarial]

    # The ten the front page offers, from the same file the interface reads.
    analytics = json.loads(
        (ROOT / "eval" / "analytics.json").read_text(encoding="utf-8"))
    for entry in analytics.get("corpora", []):
        if entry["name"] == cfg["name"]:
            return [{"q": e["q"], "id": None,
                     "adversarial": bool(e.get("adversarial"))}
                    for e in entry.get("examples", [])]
    return []


def record_reads(serve, out: Path, name: str) -> None:
    """The GET endpoints the page calls on load, captured from the real server.

    The first version of this rebuilt each payload from `corpora.describe()`,
    which was wrong in a way that returned HTTP 200: `/api/corpus` really
    answers with `active`, `sources`, `titles`, `examples` and `data_dir`, and
    `/api/corpora` answers with `{active, corpora}` rather than a list. The
    static build served well-formed JSON with the wrong keys, the interface's
    loader threw, and the page told the reader to start a server -- which is
    precisely what that build exists to avoid.

    So nothing is reimplemented here. A real server is started on an ephemeral
    port and the endpoints are fetched over HTTP, exactly as the browser will
    fetch them. The bytes recorded are the bytes served. This is the same
    reasoning as `src/test_routes.py`, and it is the rule this project has had
    to re-learn more than once: exercise the thing rather than model it.
    """
    import threading
    import urllib.request
    from http.server import ThreadingHTTPServer

    httpd = ThreadingHTTPServer(("127.0.0.1", 0), serve.Handler)
    port = httpd.server_address[1]
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    base = f"http://127.0.0.1:{port}"

    try:
        # The corpus has to be the one being recorded, because these endpoints
        # answer for whichever is active.
        urllib.request.urlopen(urllib.request.Request(
            f"{base}/api/corpus/select",
            data=json.dumps({"name": name}).encode(),
            headers={"Content-Type": "application/json"}), timeout=120).read()

        for endpoint, filename in (("/api/corpus", "corpus.json"),
                                   ("/api/corpora", "corpora.json"),
                                   ("/api/chunks", "chunks.json"),
                                   ("/api/eval", "eval.json")):
            body = urllib.request.urlopen(base + endpoint, timeout=180).read()
            (out / filename).write_bytes(body)
    finally:
        httpd.shutdown()
        httpd.server_close()


def write_site(out: Path, manifest: dict) -> None:
    """Copy the interface next to the recordings and wire it to read them.

    The page is unchanged. A small script installed before it intercepts
    `fetch` and answers from the recorded files instead of from a server --
    which keeps the static build honest: it is the same interface, not a
    reimplementation that could drift from it.
    """
    import shutil

    ui = Path(__file__).parent.parent / "ui"
    site = out / "site"
    if site.exists():
        shutil.rmtree(site)
    site.mkdir(parents=True)

    for item in ui.iterdir():
        if item.is_dir():
            shutil.copytree(item, site / item.name)
        else:
            shutil.copy2(item, site / item.name)

    # The recordings, beside the page that reads them.
    data = site / "recorded"
    if data.exists():
        shutil.rmtree(data)
    shutil.copytree(out, data, ignore=shutil.ignore_patterns("site"))

    (site / "offline.js").write_text(OFFLINE_JS, encoding="utf-8")

    # EVERY page, not just the front one. The quality dashboard and the about
    # page call /api/ too, and injecting into index.html alone left them making
    # real requests to a server that is not there -- which showed up as a 404
    # in the console of two of the three pages and nowhere else.
    for page in sorted(site.glob("*.html")):
        html = page.read_text(encoding="utf-8")
        if "offline.js" in html:
            continue
        tag = '<script src="offline.js"></script>'
        if "<head>" in html:
            html = html.replace("<head>", "<head>\n" + tag, 1)
        else:
            html = tag + "\n" + html
        page.write_text(html, encoding="utf-8")

    (out / "vercel.json").write_text(json.dumps({
        "$schema": "https://openapi.vercel.sh/vercel.json",
        "outputDirectory": "site",
        "cleanUrls": True,
        "headers": [{
            "source": "/recorded/(.*)",
            "headers": [{"key": "Cache-Control",
                         "value": "public, max-age=31536000, immutable"}],
        }],
    }, indent=1), encoding="utf-8")


OFFLINE_JS = r"""// Answers the interface's own fetches from recorded files, so the page runs
// with no server behind it.
//
// The page is not modified beyond loading this script. That is deliberate: a
// static build that reimplemented the interface would be a second thing to keep
// in step, and this project has spent a lot of effort on exactly that class of
// bug -- two code paths that agree until one is edited.
(function () {
  // Where the recordings are, resolved from this script's own URL rather than
  // written as "/recorded/...". Absolute paths only work when the site is the
  // root of a domain: opened from disk with file:// they resolve to the
  // filesystem root, and under a project subpath (GitHub Pages serves at
  // /<repo>/) they resolve above the site. Both fail the same way -- the page
  // loads, every data fetch 404s, and the interface reports "Server
  // unreachable", which sends a reader off to start a server that this build
  // exists specifically to avoid needing.
  const HERE = new URL("./", document.currentScript
    ? document.currentScript.src
    : location.href).href;
  const at = (p) => HERE + p.replace(/^\//, "");

  // The interface reads this to know which of the two builds it is running in.
  // It is set before anything else so that a failure during the manifest fetch
  // still finds it -- the page's own error path is one of its readers, and the
  // thing that path most needs to know is whether telling someone to start a
  // server is sensible advice.
  window.RECORDED_BUILD = true;

  const KEY = (q) => {
    // Must match src/record_static.py's key(): sha256 of the trimmed,
    // lowercased question, first 16 hex characters.
    const bytes = new TextEncoder().encode(q.trim().toLowerCase());
    return crypto.subtle.digest("SHA-256", bytes).then((buf) =>
      Array.from(new Uint8Array(buf))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("")
        .slice(0, 16));
  };

  let corpus = null;
  const base = () => at(`recorded/${corpus || MANIFEST.default}`);

  // A loading state, because the first paint waits on a fetch. Injected from
  // here rather than added to the page: the live interface has a server that
  // answers in milliseconds and needs none of this, and the static build should
  // not leave a spinner in the markup that never fires there.
  const veil = document.createElement("div");
  veil.id = "recorded-loading";
  veil.innerHTML =
    '<div class="rl-inner">' +
    '<div class="rl-bars"><i></i><i></i><i></i><i></i><i></i></div>' +
    '<p class="rl-title">Loading the recorded traces</p>' +
    '<p class="rl-sub">The pipeline answered these questions in advance and ' +
    'wrote each answer to a file. No model runs behind this page.</p>' +
    "</div>";
  const style = document.createElement("style");
  style.textContent = `
    #recorded-loading{position:fixed;inset:0;z-index:9999;display:grid;
      place-items:center;background:var(--ground,#0e0e0f);
      transition:opacity .45s cubic-bezier(.23,1,.32,1)}
    #recorded-loading.gone{opacity:0;pointer-events:none}
    #recorded-loading .rl-inner{text-align:center;max-width:34rem;padding:0 1.5rem}
    #recorded-loading .rl-bars{display:flex;gap:6px;justify-content:center;
      height:44px;align-items:flex-end;margin-bottom:1.5rem}
    /* Five bars, because the pipeline has five stages and the thing being
       waited on is those stages' recorded output. A generic spinner would say
       nothing; this at least rhymes with what is loading. */
    #recorded-loading .rl-bars i{width:6px;height:12px;border-radius:2px;
      background:currentColor;opacity:.5;
      animation:rl 1.1s cubic-bezier(.23,1,.32,1) infinite}
    #recorded-loading .rl-bars i:nth-child(2){animation-delay:.09s}
    #recorded-loading .rl-bars i:nth-child(3){animation-delay:.18s}
    #recorded-loading .rl-bars i:nth-child(4){animation-delay:.27s}
    #recorded-loading .rl-bars i:nth-child(5){animation-delay:.36s}
    @keyframes rl{0%,100%{height:12px;opacity:.35}45%{height:40px;opacity:1}}
    #recorded-loading .rl-title{font-size:.95rem;margin:0 0 .5rem;
      letter-spacing:.01em}
    #recorded-loading .rl-sub{font-size:.8rem;opacity:.6;line-height:1.55;margin:0}
    @media (prefers-reduced-motion:reduce){
      #recorded-loading .rl-bars i{animation:none;height:26px}
      #recorded-loading{transition:none}
    }`;
  const mount = () => {
    document.head.appendChild(style);
    document.body.appendChild(veil);
  };
  if (document.body) mount();
  else document.addEventListener("DOMContentLoaded", mount);

  const dismiss = () => {
    veil.classList.add("gone");
    setTimeout(() => veil.remove(), 500);
  };

  // A visitor who is not told otherwise will reasonably assume the search runs
  // when they press the button. It does not: it ran months ago on a laptop and
  // the result was written to a file. The strip says so once, at the top of
  // every page, and points at the version that does run.
  const strip = document.createElement("div");
  strip.id = "recorded-strip";
  strip.innerHTML =
    '<b>Recorded demo.</b> The pipeline answered these questions in advance ' +
    'and wrote each answer to a file. No model runs behind this page, so it ' +
    'answers the questions it was given and no others. ' +
    '<a href="https://github.com/ArdellAlfatih/rag-project">Run it locally</a>' +
    ' to search your own documents.';
  const stripStyle = document.createElement("style");
  stripStyle.textContent = `
    #recorded-strip{font:400 12.5px/1.55 var(--sans,system-ui,sans-serif);
      padding:16px 20px 22px;text-align:center;
      color:var(--dim,#a2a5a7);background:var(--card,#171819);
      border-top:1px solid var(--hair,#292b2d)}
    #recorded-strip b{color:var(--ink,#f2f2f0);font-weight:600}
    #recorded-strip a{color:inherit;text-decoration:underline;
      text-underline-offset:2px}
    #recorded-strip a:hover{color:var(--ink,#f2f2f0)}
    @media (max-width:640px){#recorded-strip{padding:14px 14px 20px;
      font-size:11.5px}}`;
  const banner = () => {
    document.head.appendChild(stripStyle);
    document.body.appendChild(strip);
  };
  if (document.body) banner();
  else document.addEventListener("DOMContentLoaded", banner);

  let MANIFEST = { default: null, corpora: {} };
  const ready = fetch(at("recorded/manifest.json"))
    .then((r) => r.json())
    .then((m) => {
      MANIFEST = m;
      MANIFEST.default = Object.keys(m.corpora)[0];
      corpus = MANIFEST.default;
      return m;
    })
    .finally(() => {
      // Dismissed on settle rather than on success: if the manifest is missing
      // the page should show its own error, not sit behind a veil that never
      // lifts. A loading state that can outlive the load is worse than none.
      if (document.body) dismiss();
      else document.addEventListener("DOMContentLoaded", dismiss);
    });

  // Which corpus holds which question, read from the index each corpus already
  // ships. The first version probed instead -- fetching /recorded/<corpus>/<k>
  // for each corpus until one hit -- which worked and logged a 404 to the
  // console for every miss. A console error on a working page is how a reader
  // decides not to trust the rest of it.
  let LOCATIONS = null;
  async function locate(k) {
    if (!LOCATIONS) {
      LOCATIONS = {};
      await Promise.all(
        Object.keys(MANIFEST.corpora).map((c) =>
          real(at(`recorded/${c}/index.json`))
            .then((r) => (r.ok ? r.json() : []))
            .then((rows) => {
              for (const row of rows) {
                if (!(row.key in LOCATIONS)) LOCATIONS[row.key] = c;
              }
            })
            .catch(() => {})));
    }
    return LOCATIONS[k] || null;
  }

  const json = (data, status = 200) =>
    new Response(JSON.stringify(data), {
      status,
      headers: { "Content-Type": "application/json" },
    });

  const real = window.fetch.bind(window);

  window.fetch = async function (input, init) {
    const url = typeof input === "string" ? input : input.url;
    const path = url.replace(/^https?:\/\/[^/]+/, "").split("?")[0];
    if (!path.startsWith("/api/")) return real(input, init);
    await ready;

    if (path === "/api/corpus") return real(`${base()}/corpus.json`);
    if (path === "/api/corpora") return real(`${base()}/corpora.json`);
    if (path === "/api/chunks") return real(`${base()}/chunks.json`);
    if (path === "/api/analytics") return real(at("recorded/analytics.json"));
    if (path === "/api/eval") return real(`${base()}/eval.json`);

    if (path === "/api/corpus/select") {
      const body = JSON.parse((init && init.body) || "{}");
      if (MANIFEST.corpora[body.name]) corpus = body.name;
      return real(`${base()}/corpus.json`);
    }

    if (path === "/api/chat" || path === "/ask" || path === "/api/trace") {
      const body = JSON.parse((init && init.body) || "{}");
      const question = (body.question || "").trim();
      if (!question) return json({ error: "field 'question' is required" }, 400);
      const k = await KEY(question);
      const home = await locate(k);
      if (home) {
        // Follow the question into whichever corpus recorded it. Someone who
        // types a question from the bird set while the papers are selected
        // means the question, not the corpus.
        if (home !== corpus) corpus = home;
        return real(at(`recorded/${home}/${k}.json`));
      }
      // The honest failure. A recorded demo cannot answer a question nobody
      // recorded, and saying so is better than an empty result that reads as
      // the retrieval having failed.
      // The message goes in `error` because that is the field the interface
      // renders. Putting the explanation somewhere the page does not read
      // would show a visitor the string "not-recorded" and nothing else,
      // which is how the first version of this failed.
      const total = Object.values(MANIFEST.corpora)
        .reduce((n, c) => n + (c.questions || 0), 0);
      return json({
        error:
          "This demo is a recording: " + total + " questions, each answered " +
          "in advance and written to a file. No model runs behind this page, " +
          "so it cannot answer a new one. Pick a question from the list to " +
          "watch the search that produced it, or run the project locally to " +
          "ask your own.",
        code: "not-recorded",
      }, 404);
    }

    if (path.startsWith("/api/index/")) {
      return json({ error: "read-only", message:
        "The recorded demo cannot index documents." }, 405);
    }
    return json({ error: `no recorded route ${path}` }, 404);
  };
})();
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", action="append")
    ap.add_argument("--all", action="store_true",
                    help="every golden-set question, not just the offered ten")
    ap.add_argument("--generate", action="store_true",
                    help="also record prose from the local model")
    ap.add_argument("--site-only", action="store_true",
                    help="rebuild the page from ui/ around existing recordings; "
                         "no models are loaded and nothing is re-recorded")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    # Before `import serve`, which loads the index and both models. A rebuild
    # of the page needs neither, and this is the whole point of the flag.
    if args.site_only:
        manifest_path = args.out / "manifest.json"
        if not manifest_path.exists():
            print(f"--site-only needs recordings in {args.out}/ — "
                  f"no manifest.json there. Record once first.")
            return 2
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        write_site(args.out, manifest)
        total = sum(c["questions"] for c in manifest["corpora"].values())
        print(f"  page rebuilt from ui/ around {total} recorded question(s), "
              f"recorded {manifest.get('recorded', 'unknown')}")
        return 0

    import serve

    reg = corpora.registry()
    manifest = {"generated_by": "src/record_static.py",
                "recorded": time.strftime("%Y-%m-%d"),
                "generation": None, "corpora": {}}

    # Recording one corpus must not evict the others. Their files are still on
    # disk; without this the manifest stops naming them, the page never learns
    # they exist, and nothing anywhere reports a problem -- the demo simply
    # comes back smaller. Entries for corpora this run does not touch are
    # carried forward, and any whose folder has since gone are dropped.
    existing = args.out / "manifest.json"
    if existing.exists():
        try:
            prior = json.loads(existing.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            prior = {}
        for name, entry in (prior.get("corpora") or {}).items():
            if (args.out / name / "index.json").exists():
                manifest["corpora"][name] = entry

    if args.generate:
        import generate_local
        if not generate_local.available():
            print(f"--generate needs Ollama; none at {generate_local.HOST}")
            return 2
        manifest["generation"] = {
            "model": generate_local.MODEL,
            "note": "Prose was written by a small local model, not by a "
                    "frontier one. Attribute it as such wherever it is shown.",
        }

    for name in (args.corpus or list(reg)):
        cfg = reg.get(name)
        if not cfg or not cfg["indexed"] or not cfg["golden"]:
            continue
        serve.RES.load(name)
        items = questions_for(cfg, args.all)
        if not items:
            print(f"  {name}: no questions to record")
            continue

        corpus_dir = args.out / name
        corpus_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n  {cfg['label']}: recording {len(items)} question(s)")

        index = []
        for item in items:
            started = time.perf_counter()
            payload = serve.chat(item["q"], {})
            if args.generate:
                import generate_local
                passages = [serve.RES.metadata[i["chunk_id"]]
                            for i in payload["stages"][-1]["items"]]
                try:
                    payload["generation"] = {
                        "state": "ok",
                        "text": generate_local.synthesize(item["q"], passages),
                        "model": generate_local.MODEL,
                        "reason": None,
                    }
                except Exception as exc:                        # noqa: BLE001
                    payload["generation"] = {"state": "unavailable", "text": None,
                                             "model": generate_local.MODEL,
                                             "reason": str(exc)}
            k = key(item["q"])
            (corpus_dir / f"{k}.json").write_text(
                json.dumps(payload, indent=1), encoding="utf-8")
            index.append({"key": k, "question": item["q"], "id": item["id"],
                          "adversarial": item["adversarial"],
                          "confident": payload["verdict"].get("confident")})
            print(f"    {k}  {time.perf_counter() - started:5.1f}s  "
                  f"{item['q'][:58]}")

        (corpus_dir / "index.json").write_text(
            json.dumps(index, indent=1), encoding="utf-8")
        record_reads(serve, corpus_dir, name)
        manifest["corpora"][name] = {
            "label": cfg["label"], "questions": len(index),
            **{k: v for k, v in corpora.describe(cfg).items()
               if k in ("documents", "chunks", "formats", "threshold")},
        }

    if not manifest["corpora"]:
        print("nothing recorded")
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    # Registry order, not "whichever was recorded most recently". The default
    # corpus is what a visitor lands on, and that should not depend on which
    # one someone happened to re-record last.
    manifest["corpora"] = {name: manifest["corpora"][name]
                           for name in reg if name in manifest["corpora"]}
    manifest["default"] = next(iter(manifest["corpora"]), None)
    (args.out / "manifest.json").write_text(
        json.dumps(manifest, indent=1), encoding="utf-8")

    # The evaluation figures the quality page draws, copied rather than
    # regenerated so the static build shows the same numbers as the live one.
    for src_name, dest in (("analytics.json", "analytics.json"),):
        src_path = ROOT / "eval" / src_name
        if src_path.exists():
            (args.out / dest).write_text(
                src_path.read_text(encoding="utf-8"), encoding="utf-8")

    write_site(args.out, manifest)
    total = sum(c["questions"] for c in manifest["corpora"].values())
    size = sum(f.stat().st_size for f in args.out.rglob("*.json"))
    print(f"\n  {total} question(s), {size / 1e6:.1f} MB in "
          f"{args.out.name}/ — no models needed to serve this")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
