"""Record real traces to JSON, so the demo can be served with no models at all.

The live system needs ~1.5 GB of dependencies and 2 GB of RAM because it holds a
FAISS index, a bi-encoder and a cross-encoder in memory. That rules out every
serverless platform. But a visitor to a *demo* mostly clicks the questions the
front page offers, and those are known in advance -- so their answers can be
computed once, here, on a machine that has the models, and served afterwards by
anything that can return a JSON file.

**What is recorded is not a summary.** Each entry is the exact payload
`/api/chat` returns for that question: every retrieval stage with its ranking
and scores, the fusion arithmetic, what the reranker moved, what the diversity
cap dropped, the verdict and its threshold, and the term attribution. A static
demo built from this shows the same pipeline the live one does, because it is
the same output.

**What it loses**, stated plainly because it is the whole trade: a visitor
cannot ask a question that was not recorded. There is no model to answer one.
A static build should say so rather than presenting a text box that silently
only accepts ten strings.

Generated prose is recorded too when `--generate` is passed, and is labelled in
the payload with the model that wrote it. The interface should attribute it the
same way: "generated by llama3.2" is a materially different claim from an answer
written by a frontier model, and a reader is entitled to know which they are
reading.

    .venv\\Scripts\\python.exe src\\record_static.py --corpus birds
    .venv\\Scripts\\python.exe src\\record_static.py --all --generate
"""
import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import corpora  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent.parent
OUT = ROOT / "static-demo"


def key(question: str) -> str:
    """A stable filename for a question, so the front end can find it.

    A hash rather than a slug: questions contain punctuation, they differ in
    ways a slug flattens ("what is X?" and "what is X" would collide), and the
    front end can compute the same hash from the string it holds.
    """
    return hashlib.sha256(question.strip().lower().encode()).hexdigest()[:16]


def questions_for(cfg: dict, every: bool) -> list[dict]:
    """The questions to record: the offered ones, or the whole golden set."""
    from check_freshness import artefact_suffix
    from evaluate import load_cases

    if every:
        answerable, adversarial = load_cases(cfg["golden"])
        return [{"q": c["question"], "id": c["id"],
                 "adversarial": bool(c.get("unanswerable"))}
                for c in answerable + adversarial]

    # The ten the front page offers, from the same file the interface reads.
    analytics = json.loads(
        (ROOT / "eval" / "analytics.json").read_text(encoding="utf-8"))
    for entry in analytics.get("corpora", []):
        if entry["name"] == cfg["name"]:
            return [{"q": e["q"], "id": None,
                     "adversarial": bool(e.get("adversarial"))}
                    for e in entry.get("examples", [])]
    return []


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", action="append")
    ap.add_argument("--all", action="store_true",
                    help="every golden-set question, not just the offered ten")
    ap.add_argument("--generate", action="store_true",
                    help="also record prose from the local model")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    import serve

    reg = corpora.registry()
    manifest = {"generated_by": "src/record_static.py",
                "recorded": time.strftime("%Y-%m-%d"),
                "generation": None, "corpora": {}}

    if args.generate:
        import generate_local
        if not generate_local.available():
            print(f"--generate needs Ollama; none at {generate_local.HOST}")
            return 2
        manifest["generation"] = {
            "model": generate_local.MODEL,
            "note": "Prose was written by a small local model, not by a "
                    "frontier one. Attribute it as such wherever it is shown.",
        }

    for name in (args.corpus or list(reg)):
        cfg = reg.get(name)
        if not cfg or not cfg["indexed"] or not cfg["golden"]:
            continue
        serve.RES.load(name)
        items = questions_for(cfg, args.all)
        if not items:
            print(f"  {name}: no questions to record")
            continue

        corpus_dir = args.out / name
        corpus_dir.mkdir(parents=True, exist_ok=True)
        print(f"\n  {cfg['label']}: recording {len(items)} question(s)")

        index = []
        for item in items:
            started = time.perf_counter()
            payload = serve.chat(item["q"], {})
            if args.generate:
                import generate_local
                passages = [serve.RES.metadata[i["chunk_id"]]
                            for i in payload["stages"][-1]["items"]]
                try:
                    payload["generation"] = {
                        "state": "ok",
                        "text": generate_local.synthesize(item["q"], passages),
                        "model": generate_local.MODEL,
                        "reason": None,
                    }
                except Exception as exc:                        # noqa: BLE001
                    payload["generation"] = {"state": "unavailable", "text": None,
                                             "model": generate_local.MODEL,
                                             "reason": str(exc)}
            k = key(item["q"])
            (corpus_dir / f"{k}.json").write_text(
                json.dumps(payload, indent=1), encoding="utf-8")
            index.append({"key": k, "question": item["q"], "id": item["id"],
                          "adversarial": item["adversarial"],
                          "confident": payload["verdict"].get("confident")})
            print(f"    {k}  {time.perf_counter() - started:5.1f}s  "
                  f"{item['q'][:58]}")

        (corpus_dir / "index.json").write_text(
            json.dumps(index, indent=1), encoding="utf-8")
        manifest["corpora"][name] = {
            "label": cfg["label"], "questions": len(index),
            **{k: v for k, v in corpora.describe(cfg).items()
               if k in ("documents", "chunks", "formats", "threshold")},
        }

    if not manifest["corpora"]:
        print("nothing recorded")
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "manifest.json").write_text(
        json.dumps(manifest, indent=1), encoding="utf-8")
    total = sum(c["questions"] for c in manifest["corpora"].values())
    size = sum(f.stat().st_size for f in args.out.rglob("*.json"))
    print(f"\n  {total} question(s), {size / 1e6:.1f} MB in "
          f"{args.out.name}/ — no models needed to serve this")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
